#默认使用配置
spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-request-size: 100Mb
      max-file-size: 10Mb
#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.f22pkj31.bean
  mapperLocations: classpath:mapper/*.xml
server:
  servlet:
    context-path: /leadcampus
web:
  upload-path: C:/2_workspace/6_Files/leadcompusfile/
#  upload-path: /home/tomcat/apache-tomcat-8.5.8/webapps/leadcompusfile/
logging:
  level.root: info
  level.org.springframework.web: debug
  level.com.f22pkj31: debug
---
#开发配置

spring:
  profiles: dev
  mvc.static-path-pattern: /**
  resources.static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
  datasource:
    url: jdbc:mysql://47.95.14.18:3306/leadcampus?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: uAiqwVwjJ8-i
    driver-class-name: com.mysql.jdbc.Driver
server:
  tomcat:
    max-http-post-size: 0

